return {
  --   "nvim-treesitter/nvim-treesitter",
  --   build = ":TSUpdate",
  --   opts = {
  --     ensure_installed = { "c", "lua", "vim", "vimdoc", "query" },
  --     highlight = { enable = true },
  --   },
  --   config = function(_, opts)
  --     require("nvim-treesitter.configs").setup(opts)
  --   end,
  -- }, {
  --   "nvim-neorg/neorg",
  --   lazy = false,
  --   version = "*",
  --   config = function()
  --     require("neorg").setup({
  --       load = {
  --         ["core.defaults"] = {},
  --         ["core.concealer"] = {},
  --         ["core.dirman"] = {
  --           config = {
  --             workspaces = {
  --               notes = "~/.config/notes",
  --               projects = "~/.config/notes/projects/",
  --             },
  --             default_workspace = "projects",
  --           },
  --         },
  --       },
  --     })
  --   end,
}
